//! Bundled grammar pack: curated subcommand/flag tables for common CLI tools.
//! Ordering within each list is the rank order (most common first).

use super::grammar::{Subcommand, ToolGrammar};

macro_rules! sub {
    ($name:literal) => {
        Subcommand {
            name: $name,
            flags: &[],
        }
    };
    ($name:literal, $flags:expr) => {
        Subcommand {
            name: $name,
            flags: $flags,
        }
    };
}

pub(crate) static GRAMMARS: &[ToolGrammar] = &[
    ToolGrammar {
        name: "git",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("status", &["-s", "--short", "-b"]),
            sub!("add", &["-A", "-p", "-u"]),
            sub!("commit", &["-m", "-a", "--amend", "--no-edit", "-v"]),
            sub!("push", &["-u", "--force-with-lease", "--tags", "--dry-run"]),
            sub!("pull", &["--rebase", "--ff-only"]),
            sub!("checkout", &["-b", "--"]),
            sub!("branch", &["-d", "-D", "-a", "--show-current"]),
            sub!("switch", &["-c", "--detach"]),
            sub!("diff", &["--staged", "--stat", "--name-only"]),
            sub!("log", &["--oneline", "--graph", "-p", "--stat"]),
            sub!("stash", &["--include-untracked"]),
            sub!("fetch", &["--all", "--prune"]),
            sub!("merge", &["--no-ff", "--abort", "--squash"]),
            sub!("rebase", &["--continue", "--abort", "--onto"]),
            sub!("clone", &["--depth", "--branch"]),
            sub!("restore", &["--staged", "--source"]),
            sub!("reset", &["--hard", "--soft", "--mixed"]),
            sub!("remote", &["-v"]),
            sub!("tag", &["-a", "-d", "-l"]),
            sub!("show", &["--stat", "--name-only"]),
            sub!("cherry-pick", &["--continue", "--abort"]),
            sub!("revert", &["--no-edit", "--continue"]),
            sub!("rm", &["-r", "--cached"]),
            sub!("mv", &[]),
            sub!("init", &["--bare"]),
            sub!("blame", &["-L"]),
            sub!("grep", &["-n", "-i"]),
            sub!("reflog", &[]),
            sub!("worktree", &[]),
            sub!("bisect", &[]),
        ],
    },
    ToolGrammar {
        name: "cargo",
        global_flags: &["--help", "--version", "--locked", "--offline"],
        subcommands: &[
            sub!(
                "build",
                &["--release", "--workspace", "-p", "--all-targets"]
            ),
            sub!("run", &["--release", "-p", "--bin", "--example"]),
            sub!("test", &["--workspace", "--release", "-p", "--no-run"]),
            sub!("check", &["--workspace", "--all-targets"]),
            sub!("clippy", &["--workspace", "--all-targets", "--fix"]),
            sub!("fmt", &["--all", "--check"]),
            sub!("add", &["--dev", "--features", "--no-default-features"]),
            sub!("remove", &["--dev"]),
            sub!("update", &["-p", "--dry-run"]),
            sub!("install", &["--path", "--force"]),
            sub!("new", &["--lib", "--bin"]),
            sub!("doc", &["--open", "--no-deps"]),
            sub!("clean", &["--release"]),
            sub!("bench", &[]),
            sub!("publish", &["--dry-run"]),
        ],
    },
    ToolGrammar {
        name: "docker",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("run", &["-it", "-d", "--rm", "-p", "-v", "--name", "-e"]),
            sub!("ps", &["-a", "-q"]),
            sub!("build", &["-t", "-f", "--no-cache"]),
            sub!("exec", &["-it", "-u"]),
            sub!("logs", &["-f", "--tail"]),
            sub!("compose", &["-f", "-d"]),
            sub!("images", &["-q"]),
            sub!("pull", &[]),
            sub!("push", &[]),
            sub!("stop", &[]),
            sub!("start", &[]),
            sub!("restart", &[]),
            sub!("rm", &["-f", "-v"]),
            sub!("rmi", &["-f"]),
            sub!("inspect", &["--format"]),
            sub!("network", &[]),
            sub!("volume", &[]),
            sub!("system", &[]),
            sub!("kill", &[]),
        ],
    },
    ToolGrammar {
        name: "brew",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("install", &["--cask", "--head"]),
            sub!("upgrade", &["--cask"]),
            sub!("update", &[]),
            sub!("uninstall", &["--zap"]),
            sub!("search", &["--cask"]),
            sub!("list", &["--cask", "--versions"]),
            sub!("info", &["--cask"]),
            sub!("services", &[]),
            sub!("tap", &[]),
            sub!("untap", &[]),
            sub!("outdated", &["--cask"]),
            sub!("cleanup", &["-s", "--prune"]),
            sub!("doctor", &[]),
            sub!("leaves", &[]),
            sub!("link", &["--overwrite"]),
        ],
    },
    ToolGrammar {
        name: "npm",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("install", &["--save-dev", "-g", "--legacy-peer-deps"]),
            sub!("run", &["--silent"]),
            sub!("test", &[]),
            sub!("start", &[]),
            sub!("init", &["-y"]),
            sub!("uninstall", &["-g", "--save-dev"]),
            sub!("update", &["-g"]),
            sub!("outdated", &["-g"]),
            sub!("list", &["-g", "--depth"]),
            sub!("audit", &["--fix"]),
            sub!("publish", &["--dry-run", "--access"]),
            sub!("ci", &[]),
            sub!("link", &[]),
            sub!("version", &["patch", "minor", "major"]),
        ],
    },
    ToolGrammar {
        name: "pnpm",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("add", &["-D", "-g", "--save-peer"]),
            sub!("install", &["--frozen-lockfile"]),
            sub!("run", &[]),
            sub!("test", &[]),
            sub!("dev", &[]),
            sub!("build", &[]),
            sub!("remove", &["-D", "-g"]),
            sub!("update", &["--latest", "-i"]),
            sub!("list", &["-g", "--depth"]),
            sub!("link", &["-g"]),
        ],
    },
    ToolGrammar {
        name: "yarn",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("add", &["-D", "-P", "-O"]),
            sub!("install", &["--frozen-lockfile", "--immutable"]),
            sub!("run", &[]),
            sub!("test", &[]),
            sub!("dev", &[]),
            sub!("build", &[]),
            sub!("remove", &[]),
            sub!("upgrade", &["--latest"]),
            sub!("link", &[]),
        ],
    },
    ToolGrammar {
        name: "kubectl",
        global_flags: &["--help", "-n", "--context", "--kubeconfig"],
        subcommands: &[
            sub!("get", &["-A", "-n", "-o", "-w", "--show-labels"]),
            sub!("apply", &["-f", "-k", "--dry-run"]),
            sub!("describe", &["-n"]),
            sub!("logs", &["-f", "--tail", "-n", "--previous"]),
            sub!("exec", &["-it", "-n", "--"]),
            sub!("delete", &["-f", "-n", "--force"]),
            sub!("create", &["-f", "-n"]),
            sub!("edit", &["-n"]),
            sub!("rollout", &[]),
            sub!("scale", &["--replicas"]),
            sub!("port-forward", &["-n"]),
            sub!("config", &[]),
            sub!("expose", &["--port", "--type"]),
            sub!("top", &["-n"]),
        ],
    },
    ToolGrammar {
        name: "gh",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("pr", &["--web"]),
            sub!("issue", &["--web"]),
            sub!("repo", &[]),
            sub!("run", &[]),
            sub!("release", &[]),
            sub!("auth", &[]),
            sub!("browse", &[]),
            sub!("gist", &[]),
            sub!("workflow", &[]),
            sub!("label", &[]),
            sub!("api", &["--method", "--paginate"]),
        ],
    },
    ToolGrammar {
        name: "go",
        global_flags: &["--help"],
        subcommands: &[
            sub!("build", &["-o", "-race", "-v"]),
            sub!("run", &["-race"]),
            sub!("test", &["-v", "-run", "-count", "-race", "-cover"]),
            sub!("mod", &[]),
            sub!("get", &["-u"]),
            sub!("install", &[]),
            sub!("fmt", &[]),
            sub!("vet", &[]),
            sub!("generate", &[]),
            sub!("doc", &["-all"]),
            sub!("env", &["-w"]),
            sub!("list", &["-m", "-json"]),
            sub!("clean", &["-cache", "-testcache"]),
            sub!("version", &[]),
            sub!("tool", &[]),
            sub!("work", &[]),
        ],
    },
    ToolGrammar {
        name: "rustup",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("update", &["--force"]),
            sub!("default", &[]),
            sub!("show", &["active-toolchain"]),
            sub!("target", &[]),
            sub!("component", &[]),
            sub!("toolchain", &[]),
            sub!("override", &[]),
            sub!("install", &[]),
            sub!("check", &[]),
            sub!("which", &[]),
            sub!("doc", &["--std", "--book"]),
        ],
    },
    ToolGrammar {
        name: "pip",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("install", &["-U", "-r", "-e", "--user", "--no-cache-dir"]),
            sub!("uninstall", &["-y", "-r"]),
            sub!("list", &["--outdated", "--user"]),
            sub!("freeze", &["--user"]),
            sub!("show", &["-f"]),
            sub!("download", &["-r", "-d"]),
            sub!("check", &[]),
            sub!("config", &[]),
            sub!("wheel", &["-r"]),
        ],
    },
    ToolGrammar {
        name: "uv",
        global_flags: &["--help", "--version"],
        subcommands: &[
            sub!("sync", &["--frozen", "--all-extras"]),
            sub!("run", &["--with", "--frozen"]),
            sub!("add", &["--dev", "--optional"]),
            sub!("remove", &["--dev"]),
            sub!("pip", &[]),
            sub!("venv", &["--python"]),
            sub!("lock", &["--upgrade"]),
            sub!("init", &["--lib", "--app"]),
            sub!("python", &[]),
            sub!("tool", &[]),
            sub!("build", &[]),
            sub!("publish", &[]),
            sub!("tree", &["--depth"]),
        ],
    },
    ToolGrammar {
        name: "terraform",
        global_flags: &["--help", "-version"],
        subcommands: &[
            sub!("plan", &["-out", "-var-file", "-destroy"]),
            sub!("apply", &["-auto-approve", "-var-file"]),
            sub!("init", &["-upgrade", "-reconfigure"]),
            sub!("destroy", &["-auto-approve"]),
            sub!("validate", &[]),
            sub!("fmt", &["-recursive", "-check"]),
            sub!("show", &["-json"]),
            sub!("output", &["-json"]),
            sub!("state", &[]),
            sub!("import", &[]),
            sub!("workspace", &[]),
            sub!("refresh", &[]),
            sub!("providers", &[]),
            sub!("console", &[]),
            sub!("graph", &[]),
            sub!("taint", &[]),
            sub!("untaint", &[]),
            sub!("get", &["-update"]),
            sub!("version", &[]),
        ],
    },
    ToolGrammar {
        name: "tmux",
        global_flags: &["-V"],
        subcommands: &[
            sub!("new-session", &["-s", "-d", "-n"]),
            sub!("attach", &["-t", "-d"]),
            sub!("list-sessions", &[]),
            sub!("kill-session", &["-t"]),
            sub!("kill-server", &[]),
            sub!("new-window", &["-n", "-t"]),
            sub!("list-windows", &["-a"]),
            sub!("split-window", &["-h", "-v", "-t"]),
            sub!("rename-session", &["-t"]),
            sub!("switch-client", &["-t", "-n", "-p"]),
            sub!("detach", &["-s"]),
            sub!("has-session", &["-t"]),
        ],
    },
];
